//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bikes
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeModel
    {
        public int ID { get; set; }
        public int MakeID { get; set; }
        public string ModelName { get; set; }
        public string Version { get; set; }
    }
}
