//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bikes
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeRegistration
    {
        public int RegistrationNo { get; set; }
        public string Place { get; set; }
        public int NoOfOwners { get; set; }
        public string Insurance { get; set; }
        public Nullable<System.DateTime> InsuranceExpDate { get; set; }
        public Nullable<int> BikeId { get; set; }
        public int RegistrationId { get; set; }
    
        public virtual BikeRegistration BikeRegistration1 { get; set; }
        public virtual BikeRegistration BikeRegistration2 { get; set; }
    }
}
