//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bikes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BikesEntities : DbContext
    {
        public BikesEntities()
            : base("name=BikesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BikeBrand> BikeBrands { get; set; }
        public DbSet<BikeCondition> BikeConditions { get; set; }
        public DbSet<BikeModel> BikeModels { get; set; }
        public DbSet<BikeRegistration> BikeRegistrations { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<UsedBike> UsedBikes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Place> Places { get; set; }
        public DbSet<State> States { get; set; }
    }
}
